/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;
import java.sql.*;



/**
 *
 * @author Matt
 */
public class MainFrame extends javax.swing.JFrame {
    Conexion con = new Conexion();
    Redimensionador r = new Redimensionador();
    GestorClientes gc = new GestorClientes();
    String cliente[] = new String[7];
    
    public MainFrame() {
        initComponents();
        r.resizeImageIcon(jButtonImprimir, "src/imgs/impresora.png");
        r.resizeImageIcon(jButtonSalir, "src/imgs/cerrar.png");
        r.resizeImageIcon(jButtonClientes, "src/imgs/user.png");
        r.resizeImageIcon(jButtonBuscarCliente, "src/imgs/searching.png");
        deshabilitarCampos();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlblCliente = new javax.swing.JLabel();
        jlblProducto = new javax.swing.JLabel();
        jlblCantidad = new javax.swing.JLabel();
        jtxtCantidad = new javax.swing.JTextField();
        jcbxProducto = new javax.swing.JComboBox<>();
        jButtonAgregar = new javax.swing.JButton();
        jlblPrecio = new javax.swing.JLabel();
        jtxtPrecio = new javax.swing.JTextField();
        jlblFecha = new javax.swing.JLabel();
        jtxtFormatFecha = new javax.swing.JFormattedTextField();
        jlblVendedor = new javax.swing.JLabel();
        jcbxVendedor = new javax.swing.JComboBox<>();
        jlblVendedor1 = new javax.swing.JLabel();
        jtxtReferencia = new javax.swing.JTextField();
        jlblDisponible = new javax.swing.JLabel();
        jtxtDisponible = new javax.swing.JTextField();
        jlblPago = new javax.swing.JLabel();
        jcbxPago = new javax.swing.JComboBox<>();
        jtxtCedulaCliente = new javax.swing.JTextField();
        jButtonBuscarCliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonImprimir = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonClientes = new javax.swing.JButton();
        jPanelDetalleProductos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDatos = new javax.swing.JTable();
        jPanelDatosPieFactura = new javax.swing.JPanel();
        jlblCantidadPro = new javax.swing.JLabel();
        jtxtCantidadProducto = new javax.swing.JTextField();
        jlblEVenta = new javax.swing.JLabel();
        jtxtVenta = new javax.swing.JTextField();
        jlblPCon = new javax.swing.JLabel();
        jtxtPcon = new javax.swing.JTextField();
        jlblCambio = new javax.swing.JLabel();
        jtxtCambio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlblCliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblCliente.setText("CLIENTE");

        jlblProducto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblProducto.setText("PRODUCTO");

        jlblCantidad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblCantidad.setText("CANTIDAD");

        jcbxProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonAgregar.setText("Agregar a la Venta");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jlblPrecio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblPrecio.setText("PRECIO");

        jlblFecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblFecha.setText("FECHA");

        jtxtFormatFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jlblVendedor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblVendedor.setText("VENDEDOR");

        jcbxVendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlblVendedor1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblVendedor1.setText("REFERENCIA");

        jlblDisponible.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblDisponible.setText("DISPONIBLE");

        jlblPago.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblPago.setText("PAGO");

        jcbxPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jtxtCedulaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCedulaClienteKeyTyped(evt);
            }
        });

        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblProducto)
                    .addComponent(jlblCliente)
                    .addComponent(jlblCantidad)
                    .addComponent(jlblPrecio))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jtxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(jlblFecha))
                        .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtxtCedulaCliente, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jcbxProducto, javax.swing.GroupLayout.Alignment.LEADING, 0, 158, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtFormatFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAgregar)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblVendedor)
                    .addComponent(jlblVendedor1)
                    .addComponent(jlblDisponible)
                    .addComponent(jlblPago))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jcbxVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jtxtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbxPago, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblCliente)
                            .addComponent(jlblVendedor)
                            .addComponent(jcbxVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblProducto)
                            .addComponent(jcbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblVendedor1)
                            .addComponent(jtxtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblDisponible)
                            .addComponent(jtxtDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblCantidad)
                            .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAgregar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblPago)
                            .addComponent(jlblPrecio)
                            .addComponent(jtxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblFecha)
                            .addComponent(jcbxPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addComponent(jtxtFormatFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonImprimir.setFocusable(false);
        jButtonImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDetalleProductos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NO ID", "REFERENCIA", "PRODUCTO", "CANTIDAD", "VALOR", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(jtblDatos);

        javax.swing.GroupLayout jPanelDetalleProductosLayout = new javax.swing.GroupLayout(jPanelDetalleProductos);
        jPanelDetalleProductos.setLayout(jPanelDetalleProductosLayout);
        jPanelDetalleProductosLayout.setHorizontalGroup(
            jPanelDetalleProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetalleProductosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanelDetalleProductosLayout.setVerticalGroup(
            jPanelDetalleProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetalleProductosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanelDatosPieFactura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlblCantidadPro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblCantidadPro.setText("PRODUCTOS");

        jtxtCantidadProducto.setText("0");

        jlblEVenta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblEVenta.setText("ESTA VENTA");

        jtxtVenta.setText("0");

        jlblPCon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblPCon.setText("PAGO CON");

        jtxtPcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPconActionPerformed(evt);
            }
        });

        jlblCambio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblCambio.setText("CAMBIO");

        javax.swing.GroupLayout jPanelDatosPieFacturaLayout = new javax.swing.GroupLayout(jPanelDatosPieFactura);
        jPanelDatosPieFactura.setLayout(jPanelDatosPieFacturaLayout);
        jPanelDatosPieFacturaLayout.setHorizontalGroup(
            jPanelDatosPieFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPieFacturaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelDatosPieFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCantidadPro)
                    .addComponent(jtxtCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanelDatosPieFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblEVenta)
                    .addComponent(jtxtVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanelDatosPieFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblPCon, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPcon, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanelDatosPieFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCambio)
                    .addComponent(jtxtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanelDatosPieFacturaLayout.setVerticalGroup(
            jPanelDatosPieFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPieFacturaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelDatosPieFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCantidadPro)
                    .addComponent(jlblEVenta)
                    .addComponent(jlblPCon)
                    .addComponent(jlblCambio))
                .addGap(31, 31, 31)
                .addGroup(jPanelDatosPieFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelDetalleProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelDatosPieFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDetalleProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDatosPieFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jtxtPconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPconActionPerformed

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        // TODO add your handling code here:
        GestorClientes gc = new GestorClientes();
        gc.setParentFrame(MainFrame.this);
        gc.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jtxtCedulaClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCedulaClienteKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if (c < '0' || c > '9') {
            evt.consume();
        }
        if (jtxtCedulaCliente.getText().trim().length() >= 10){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtCedulaClienteKeyTyped

    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteActionPerformed
        // TODO add your handling code here:
        buscarCliente();
    }//GEN-LAST:event_jButtonBuscarClienteActionPerformed

    public void buscarCliente() {
        try {
            String cedula = jtxtCedulaCliente.getText().trim();

            if (!cedula.isEmpty()) {

                if (gc.validarCedula(cedula)) {
                    if (gc.existCustomer(cedula)) {
                        habilitarCampos();
                        obtenerCliente(cliente, cedula);
                        System.out.println("Nombre: " +cliente[1]+"\nApellido: "+cliente[2]); // <----- para prueba
                    }else{
                        int n = JOptionPane.showConfirmDialog(this, "Cliente no existente, desea continuar como Consumidor Final?","Cliente no encontrado",JOptionPane.YES_NO_OPTION);
                        if (n == 0) {
                            habilitarCampos();
                            consumidorFinal();
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Cédula NO válida", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } else {

                JOptionPane.showMessageDialog(this, "Para asignar una factura, ingrese la cédula", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: " +e, "RUNTIME EXCEPTION", JOptionPane.ERROR_MESSAGE);
        }

    }
    
    public void deshabilitarCampos(){
        jcbxVendedor.setEnabled(false);
        jtxtReferencia.setEnabled(false);
        jtxtDisponible.setEnabled(false);
        jcbxPago.setEnabled(false);
        jcbxProducto.setEnabled(false);
        jtxtCantidad.setEnabled(false);
        jtxtPrecio.setEnabled(false);
        jButtonAgregar.setEnabled(false);
        jtxtPrecio.setEnabled(false);
        jtxtFormatFecha.setEnabled(false);
        jtblDatos.setEnabled(false);
        jtxtCantidadProducto.setEnabled(false);
        jtxtVenta.setEnabled(false);
        jtxtPcon.setEnabled(false);
        jtxtCambio.setEnabled(false);
    }
    
    public void habilitarCampos(){
        jcbxVendedor.setEnabled(true);
        jtxtReferencia.setEnabled(true);
        jtxtDisponible.setEnabled(true);
        jcbxPago.setEnabled(true);
        jcbxProducto.setEnabled(true);
        jtxtCantidad.setEnabled(true);
        jtxtPrecio.setEnabled(true);
        jButtonAgregar.setEnabled(true);
        jtxtPrecio.setEnabled(true);
        jtxtFormatFecha.setEnabled(true);
        jtblDatos.setEnabled(true);
        jtxtCantidadProducto.setEnabled(true);
        jtxtVenta.setEnabled(true);
        jtxtPcon.setEnabled(true);
        jtxtCambio.setEnabled(true);
    }
    
    public void consumidorFinal(){
        
    }
    
    public void obtenerCliente(String cliente[], String cedula){
        try {
            String sql = "SELECT * FROM clientes WHERE CED_CLI = '"+cedula+"';";
            Connection c = con.ConexionBD();
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery(sql);
            
            while (rs.next()) {
                cliente[0] = rs.getString("CED_CLI");
                cliente[1] = rs.getString("NOM_CLI");
                cliente[2] = rs.getString("APE_CLI");
                cliente[3] = rs.getString("DIR_CLI");
                cliente[4] = rs.getString("FEC_NAC_CLI");
                cliente[5] = rs.getString("TEL_CLI");
                cliente[6] = rs.getString("COR_CLI");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: " +e, "RUNTIME EXCEPTION", JOptionPane.ERROR_MESSAGE);
        }
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDatosPieFactura;
    private javax.swing.JPanel jPanelDetalleProductos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbxPago;
    private javax.swing.JComboBox<String> jcbxProducto;
    private javax.swing.JComboBox<String> jcbxVendedor;
    private javax.swing.JLabel jlblCambio;
    private javax.swing.JLabel jlblCantidad;
    private javax.swing.JLabel jlblCantidadPro;
    private javax.swing.JLabel jlblCliente;
    private javax.swing.JLabel jlblDisponible;
    private javax.swing.JLabel jlblEVenta;
    private javax.swing.JLabel jlblFecha;
    private javax.swing.JLabel jlblPCon;
    private javax.swing.JLabel jlblPago;
    private javax.swing.JLabel jlblPrecio;
    private javax.swing.JLabel jlblProducto;
    private javax.swing.JLabel jlblVendedor;
    private javax.swing.JLabel jlblVendedor1;
    private javax.swing.JTable jtblDatos;
    private javax.swing.JTextField jtxtCambio;
    private javax.swing.JTextField jtxtCantidad;
    private javax.swing.JTextField jtxtCantidadProducto;
    private javax.swing.JTextField jtxtCedulaCliente;
    private javax.swing.JTextField jtxtDisponible;
    private javax.swing.JFormattedTextField jtxtFormatFecha;
    private javax.swing.JTextField jtxtPcon;
    private javax.swing.JTextField jtxtPrecio;
    private javax.swing.JTextField jtxtReferencia;
    private javax.swing.JTextField jtxtVenta;
    // End of variables declaration//GEN-END:variables
}
